const gifTags = [
    "Pirate",
    "Union",
    "Galactica",
    "Planet of the apes",
    "Metallica",
    "Iron Maiden",
    "Russian Lifestyle",
    "Spoiler",
    "Stupid",
    "Asshole",
    "Motley Crew",
    "Sinatra",
    "Mars",
    "Us",
    "Gateway of the mind",
    "Smile dog",
    "404",
    "Angry cat",
    "Cute cat",
    "Ricky Gervais",
    "Relax",
    "Cobra Kai",
    "Butterfly effect",
    "Axolote",
    "Ayuwoki",
    "Candle Cove",
    "The Expressionless",
    "The Russian Sleep Experiment",
    "No End's House",
    "Robert The Doll",
    "Jeff The Killer",
    "Sinyster",
    "Slender Man",
    "Hole in one",
    "Insane",
    "Firefly",
    "Buffy",
    "Not Bad",
    "Future Man",
    "Creationism",
    "Fight for your rights",
    "Bubble gum",
    "Walkman",
    "Atari",
    "Doom",
    "Shawn of the dead",
    "Kevin James",
    "McLane",
    "Russian",
    "KGB",
    "CIA",
    "FBI",
    "Snowden",
    "Cucumber",
    "Imperator Furiosa",
    "Abyss",
    "Avatar",
    "MMA",
    "UFC",
    "Coherence",
    "Black Rock",
    "Quarantine",
    "Security Breach",
    "Alert",
    "90's",
    "00's",
    "Candyman",
    "Fox",
    "Quatermass",
    "Flash Gordon",
    "Athletic Club",
    "Bilbao",
    "Guggenheim",
    "Sylvester Stallone",
    "Dolph Lundgren",
    "The Prissoner",
    "Flower Power",
    "Egg",
    "Phantomas",
    "El Santo",
    "Takeshi Kitano",
    "Animatrix",
    "Porco Rosso",
    "Sonny Crocket",
    "Miami Vice",
    "Scissor Hands",
    "Cyberdine",
    "Soylent Green",
    "Howard The Duck",
    "Choky",
    "Full Metal Jacket",
    "Fright Night",
    "Collosal",
    "Tyler Durden",
    "The Pixies",
    "Paradise",
    "Training",
    "Rainbow",
    "Psychodellic",
    "Qanom",
    "Otaku",
    "Ramen",
    "Break",
    "Worm",
    "Final Boss",
    "Far",
    "Arrow",
    "Speed",
    "Magic",
    "Shit",
    "Desperate",
    "Waiting",
    "Scared",
    "Zen",
    "Blur",
    "Fame",
    "Thug Life",
    "Gang",
    "Tony Montana",
    "Wall Street",
    "Chuck Norris",
    "Jean CLaude Van Damme",
    "Steven Seagal",
    "Flow",
    "Inspire",
    "Blow",
    "Las Vegas",
    "New York",
    "11-S",
    "Red Neck",
    "Bless",
    "Storm",
    "Bad Guy",
    "Fire",
    "Elon Musk",
    "Basket Case",
    "Jump",
    "Reborn",
    "X Rays",
    "Mulder",
    "Scully",
    "X-Files",
    "UFO",
    "Chupacabras",
    "The Changelling",
    "Mad Max",
    "DarkMan",
    "The Blob",
    "Airbag",
    "Mad Max",
    "Ronda Rousey",
    "Bipolar",
    "Asperger",
    "Caligula",
    "Stalker",
    "Solaris",
    "Fausto",
    "Doctor Caligari",
    "Lethal Weapon",
    "Top Gun",
    "Star Fighter",
    "Blondie",
    "Megan Fox",
    "Pamela Anderson",
    "True Detective",
    "Mr. T",
    "Shinsuke Nakamura",
    "British Bulldog",
    "VHS",
    "Metal Gear",
    "Son of Sam",
    "Ed Gein",
    "Stallone Cobra",
    "Dolph Lundgren",
    "Four Rooms",
    "Evil Dead",
    "Bruce Campbell",
    "America Ninja",
    "Xavier",
    "Bruce willis",
    "Yipi Kai Yei",
    "Inception",
    "Truffaut",
    "Hitchcock",
    "Twilight Zone",
    "Vertigo",
    "Psycho",
    "Brian Bosworth",
    "Barbarian Twins",
    "The Purge",
    "Snoop Dog",
    "Cujo",
    "NightBreed",
    "The Fist of The North Star",
    "Hobbo Fight",
    "Serendipity",
    "Lost Island",
    "Dharma",
    "Scare Reaction",
    "Shock",
    "Ball of Fire",
    "Chain Reaction",
    "Invisible Man",
    "Reptilian",
    "Flat Earth",
    "Illuminati",
    "The truth is out there",
    "Golem",
    "Meat Loaf",
    "Daredevil",
    "Sand Man",
    "Rollerball",
    "From Dusk Till Dawn",
    "Blaxploitation",
    "Russel Crow",
    "Blackula",
    "Foxie Brown",
    "Humungus",
    "Inmortan Joe",
    "Inmortals",
    "Route 66",
    "Christopher Lee",
    "Last Man on Earth",
    "Gina carano",
    "Bang",
    "Mushroom",
    "Flamingo",
    "Acid",
    "Techno",
    "Home Sweet Home",
    "Reanimator",
    "Tim Curry",
    "Batista",
    "Titanic",
    "Funko",
    "Venom",
    "Uncharted",
    "Flesh",
    "Mario",
    "Lannister",
    "Game of thrones",
    "Last of Us",
    "Lego",
    "Rabbid",
    "Toy Story",
    "Jackie Chan",
    "Afro",
    "Pablo Escobar",
    "The Witcher",
    "Egoland",
    "Corruption",
    "Denzel",
    "Tesla",
    "Brain",
    "Avengers assemble",
    "Shark",
    "Megalodon",
    "Jazz",
    "North Corea",
    "Fresh",
    "DJ",
    "John Carpenter",
    "Thrasher",
    "LOL",
    "Anomnymous",
    "Tarantino",
    "Friday Night Funkin",
    "Hommer",
    "Dev",
    "Among us",
    "John Cena",
    "Tommy Wisseau",
    "Sergio Leone",
    "Milk",
    "Matrix",
    "Justin Biever",
    "Jackass",
    "Damned",
    "Freddy",
    "David Hasselhoff",
    "Mr Beast",
    "Retro",
    "Fatality",
    "Tron",
    "Squid Game",
    "Hellraiser",
    "Call of Dutty",
    "Rubius",
    "Hacking",
    "South Park",
    "Attack of The Titans",
    "Charlie Sheen",
    "Samuel L Jackson",
    "Mecha",
    "Cyber-Punk",
    "Avocado",
    "Ibai",
    "Tobey MacGuire",
    "Hate",
    "Love",
    "Black Power",
    "Cuphead",
    "FNAF",
    "Death Note",
    "XD",
    "Christiano",
    "Spain",
    "Fuck",
    "Rocket",
    "Evangelion",
    "Pride",
    "Kawai",
    "The best",
    "Fail",
    "Lord of the Rings",
    "Baby Yoda",
    "Toretto",
    "Messi",
    "Apocalypse",
    "Sad",
    "Burrito",
    "Optimus",
    "Mr Robot",
    "Spiderman",
    "Superman",
    "Iron Man",
    "Captain America",
    "Thor",
    "Black Widow",
    "Wonder Woman",
    "Bat dance",
    "Rosalia",
    "Bad Bunny",
    "Norm MacDonald",
    "Bill Murray",
    "Chevy Chase",
    "Peter Griffin",
    "Trailer Park Boys",
    "Machete",
    "Miley Cyrus",
    "Fuck you",
    "War",
    "Manga",
    "Dwarf",
    "Bad News",
    "Dance",
    "Hypercube",
    "Thanos",
    "Mandalorian",
    "Grand Thaeft Auto",
    "WOW",
    "Grefg",
    "DeadMau5",
    "Snake Plissken",
    "Joker",
    "Star Wars",
    "Fool",
    "Scare",
    "OMG",
    "Pokemon",
    "Monty Python",
    "Zombie",
    "Africa",
    "Ru Paul",
    "Obey",
    "Kim Jon Un",
    "007",
    "Baki",
    "Tom Brady",
    "Akira",
    "Terminator",
    "Alien",
    "Predator",
    "Harley Queen",
    "Nicolas Cage",
    "Dune",
    "Black Lives Matter",
    "Gay Pride",
    "Machete",
    "Happy Day",
    "Working",
    "Darth Vader",
    "Survivor",
    "Streets Of Fire",
    "Old Boy",
    "Smiley",
    "Bender",
    "Ninja",
    "The Simpsons",
    "Funny",
    "Sexy",
    "Freak",
    "Danger",
    "Unicorn",
    "80's",
    "Neon",
    "Breaking Bad",
    "Samurai",
    "Scotty Piper",
    "Satan",
    "Ghost",
    "Furry",
    "Adam West",
    "Stephen Hawkins",
    "Neo",
    "Adam Sandler",
    "Hangover",
    "Party",
    "Busted",
    "Ghostbusters",
    "Heavy Metal",
    "Jodorowsky",
    "Trump",
    "Vampire",
    "Werewolf",
    "Nosferatu",
    "Paranormal",
    "Fight",
    "OK",
    "Hydra",
    "Zeitgeist",
    "Steampunk",
    "Cat",
    "Dog",
    "Cute",
    "Monster",
    "The Rock",
    "Peacemaker",
    "Warning",
    "Hashtag",
    "Corey Feldman",
    "Goonies",
    "Lost",
    "Heroe",
    "Snatch",
    "Mickey Rourke",
    "Troy McClure",
    "Joe Rogan",
    "Alex Jones",
    "Cow",
    "Incell",
    "Inferno",
    "Ozzy",
    "Kit",
    "Frankenstein",
    "Guardians of the Galaxy",
    "Covid",
    "Tsunamy",
    "Vulcano",
    "Earthquake",
    "Mechanism",
    "Loop",
    "Pain",
    "Crow",
    "Bill Murray",
    "Minecraft",
    "Sorry",
    "Flow",
    "Rising",
    "Conan",
    "Tremor",
    "Reanimator",
    "Giallo",
    "Doctor Strange",
    "Scyfy",
    "Banksy",
    "Obama",
    "Police",
    "Aquaman",
    "Real Madrid",
    "Kobey",
    "Lebron",
    "FC Barcelona",
    "Ramones",
    "Kurt Cobain",
    "Nirvana",
    "David Lynch",
    "Moon",
    "Fake news",
    "Warrior",
    "Goku",
    "Gift",
    "Cruel",
    "Wolverine",
    "Chris Farley",
    "Deathpool",
    "Balloon",
    "Oliver Atom",
    "Time Travel",
    "Black Hole",
    "Mothman",
    "LeatherFace",
    "Mike Mayers",
    "Jason",
    "Phantasma",
    "Clown",
    "Bad Santa",
    "Michael Jordan",
    "Ben Johnson",
    "Malcolm X",
    "Muhammad Ali",
    "Fail",
    "Dr Who",
    "Angry Mom",
    "Ridiculous",
    "Nuclear",
    "Morpheo",
    "One Piece",
    "Virus",
    "Jeff Goldblum",
    "Die Hard",
    "Sin City",
    "Rise by Wolves",
    "Blade Runner",
    "Asimov",
    "Carl Sagan",
    "Cenobyte",
    "Ghoulies",
    "Gremlins",
    "Silver Surfer",
    "Invisible man",
    "Metropolis",
    "URSS",
    "Dredd",
    "Skate or Die",
    "Surf",
    "WarHol",
    "Indiana Jones",
    "Phone",
    "Kurosawa",
    "John Ford",
    "Bolt",
    "Shocker",
    "Broker",
    "Wolf of Wall Street",
    "Deep Fake",
    "Star Trek",
    "David Cronemberg",
    "Crash",
    "Daft Punk",
    "Red Dead Redemption",
    "Polybius",
    "Pac Man",
    "Fired",
    "Johnny Knoxville",
    "Crack",
    "Crank",
    "Fringe",
    "Silver",
    "Gold",
    "Money",
    "Diamond",
    "Pet",
    "The Rock",
    "Hulk Hogan",
    "Bruce Lee",
    "Blade",
    "Undertaker",
    "Moustache",
    "Fascism",
    "Grave",
    "Sematary",
    "Pig",
    "Dice",
    "Chucky",
    "Lovecraft",
    "Cosmic Horror",
    "Borrower",
    "Help",
    "Miracle",
    "Beetlejuice",
    "Billion",
    "Utopia",
    "Distopia",
    "Vegeta",
    "Bulma",
    "Multiverse",
    "Cuantic",
    "Universe",
    "Climatic Change",
    "Greta Thunberg",
    "Jesus",
    "Lightsaber",
    "Fortnite",
    "Freelance",
];

export default function generateTags() {
    let randomTag = `/search/${gifTags[Math.floor(Math.random() * gifTags.length)]}`;
    return randomTag;
}